In [1]:
import pandas as pd

In [2]:
df=pd.read_csv("C:\\Users\\91830\\Downloads\\data science\\Ex_Files_Intro_Data_Science\\Exercise Files\\crime_boston.csv")

In [3]:
df

,INCIDENT_NUMBER,OFFENSE_CODE,OFFENSE_CODE_GROUP,OFFENSE_DESCRIPTION,DISTRICT,REPORTING_AREA,SHOOTING,OCCURRED_ON_DATE,YEAR,MONTH,DAY_OF_WEEK,HOUR,UCR_PART,STREET,Lat,Long,Location
0,I192064813,3006,Medical Assistance,SICK/INJURED/MEDICAL - PERSON,D14,794,NaN,2019-08-17 21:00:00,2019,8,Saturday,21,Part Three,QUINT AVE,NaN,NaN,"(0.00000000, 0.00000000)"
1,I192064810,3410,Towed,TOWED MOTOR VEHICLE,B3,435,NaN,2019-08-17 21:15:00,2019,8,Saturday,21,Part Three,PEACEVALE RD,42.287167,-71.076335,"(42.28716674, -71.07633479)"
2,I192064808,2003,Offenses Against Child / Family,CHILD ENDANGERMENT (NO ASSAULT),C11,355,NaN,2019-08-17 19:33:00,2019,8,Saturday,19,Part Two,GIBSON ST,42.297555,-71.059709,"(42.29755533, -71.05970910)"
3,I192064803,802,Simple Assault,ASSAULT SIMPLE - BATTERY,E18,554,NaN,2019-08-17 20:55:00,2019,8,Saturday,20,Part Two,METROPOLITAN AVE,42.272509,-71.123190,"(42.27250898, -71.12318965)"
4,I192064800,3114,Investigate Property,INVESTIGATE PROPERTY,E18,502,NaN,2019-08-17 19:39:00,2019,8,Saturday,19,Part Three,PHILBRICK ST,42.285459,-71.118027,"(42.28545883, -71.11802667)"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
413667,I020691165-00,3125,Warrant Arrests,WARRANT ARREST,A1,77,NaN,2019-05-23 08:00:00,2019,5,Thursday,8,Part Three,NEW SUDBURY ST,42.361839,-71.059765,"(42.36183857, -71.05976489)"
413668,I020674147-00,3125,Warrant Arrests,WARRANT ARREST,A1,77,NaN,2019-05-23 08:00:00,2019,5,Thursday,8,Part Three,NEW SUDBURY ST,42.361839,-71.059765,"(42.36183857, -71.05976489)"
413669,I020669075-00,3125,Warrant Arrests,WARRANT ARREST,A1,77,NaN,2019-05-23 08:00:00,2019,5,Thursday,8,Part Three,NEW SUDBURY ST,42.361839,-71.059765,"(42.36183857, -71.05976489)"
413670,I020662996-00,3125,Warrant Arrests,WARRANT ARREST,A1,77,NaN,2019-05-23 08:56:00,2019,5,Thursday,8,Part Three,NEW SUDBURY ST,42.361839,-71.059765,"(42.36183857, -71.05976489)"
413671,I010370257-00,3125,Warrant Arrests,WARRANT ARREST,E13,569,NaN,2016-05-31 19:35:00,2016,5,Tuesday,19,Part Three,NEW WASHINGTON ST,42.302333,-71.111565,"(42.30233307, -71.11156487)"

# Read_csv Function part-2

In [4]:
# You can use haeaders to change the heading to another row...it takes parameter as the index of the row
df1=pd.read_csv("C:\\Users\\91830\\Downloads\\data science\\Ex_Files_Intro_Data_Science\\Exercise Files\\crime_boston.csv",header=1)
df1

,I192064813,03006,Medical Assistance,SICK/INJURED/MEDICAL - PERSON,D14,794,Unnamed: 6,2019-08-17 21:00:00,2019,8,Saturday,21,Part Three,QUINT AVE,Unnamed: 14,Unnamed: 15,"(0.00000000, 0.00000000)"
0,I192064810,3410,Towed,TOWED MOTOR VEHICLE,B3,435,NaN,2019-08-17 21:15:00,2019,8,Saturday,21,Part Three,PEACEVALE RD,42.287167,-71.076335,"(42.28716674, -71.07633479)"
1,I192064808,2003,Offenses Against Child / Family,CHILD ENDANGERMENT (NO ASSAULT),C11,355,NaN,2019-08-17 19:33:00,2019,8,Saturday,19,Part Two,GIBSON ST,42.297555,-71.059709,"(42.29755533, -71.05970910)"
2,I192064803,802,Simple Assault,ASSAULT SIMPLE - BATTERY,E18,554,NaN,2019-08-17 20:55:00,2019,8,Saturday,20,Part Two,METROPOLITAN AVE,42.272509,-71.123190,"(42.27250898, -71.12318965)"
3,I192064800,3114,Investigate Property,INVESTIGATE PROPERTY,E18,502,NaN,2019-08-17 19:39:00,2019,8,Saturday,19,Part Three,PHILBRICK ST,42.285459,-71.118027,"(42.28545883, -71.11802667)"
4,I192064798,3006,Medical Assistance,SICK/INJURED/MEDICAL - PERSON,B3,422,NaN,2019-08-17 19:50:00,2019,8,Saturday,19,Part Three,RIVER ST,42.271324,-71.081835,"(42.27132363, -71.08183509)"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
413666,I020691165-00,3125,Warrant Arrests,WARRANT ARREST,A1,77,NaN,2019-05-23 08:00:00,2019,5,Thursday,8,Part Three,NEW SUDBURY ST,42.361839,-71.059765,"(42.36183857, -71.05976489)"
413667,I020674147-00,3125,Warrant Arrests,WARRANT ARREST,A1,77,NaN,2019-05-23 08:00:00,2019,5,Thursday,8,Part Three,NEW SUDBURY ST,42.361839,-71.059765,"(42.36183857, -71.05976489)"
413668,I020669075-00,3125,Warrant Arrests,WARRANT ARREST,A1,77,NaN,2019-05-23 08:00:00,2019,5,Thursday,8,Part Three,NEW SUDBURY ST,42.361839,-71.059765,"(42.36183857, -71.05976489)"
413669,I020662996-00,3125,Warrant Arrests,WARRANT ARREST,A1,77,NaN,2019-05-23 08:56:00,2019,5,Thursday,8,Part Three,NEW SUDBURY ST,42.361839,-71.059765,"(42.36183857, -71.05976489)"
413670,I010370257-00,3125,Warrant Arrests,WARRANT ARREST,E13,569,NaN,2016-05-31 19:35:00,2016,5,Tuesday,19,Part Three,NEW WASHINGTON ST,42.302333,-71.111565,"(42.30233307, -71.11156487)"

In [7]:
# If your dataframe doesnot contain any header you can put it to none
df2=pd.read_csv("C:\\Users\\91830\\Downloads\\data science\\Ex_Files_Intro_Data_Science\\Exercise Files\\crime_boston.csv",skiprows=1,header=None,dtype=object)
df2

,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16
0,I192064813,03006,Medical Assistance,SICK/INJURED/MEDICAL - PERSON,D14,794,NaN,2019-08-17 21:00:00,2019,8,Saturday,21,Part Three,QUINT AVE,NaN,NaN,"(0.00000000, 0.00000000)"
1,I192064810,03410,Towed,TOWED MOTOR VEHICLE,B3,435,NaN,2019-08-17 21:15:00,2019,8,Saturday,21,Part Three,PEACEVALE RD,42.28716674,-71.07633479,"(42.28716674, -71.07633479)"
2,I192064808,02003,Offenses Against Child / Family,CHILD ENDANGERMENT (NO ASSAULT),C11,355,NaN,2019-08-17 19:33:00,2019,8,Saturday,19,Part Two,GIBSON ST,42.29755533,-71.0597091,"(42.29755533, -71.05970910)"
3,I192064803,00802,Simple Assault,ASSAULT SIMPLE - BATTERY,E18,554,NaN,2019-08-17 20:55:00,2019,8,Saturday,20,Part Two,METROPOLITAN AVE,42.27250898,-71.12318965,"(42.27250898, -71.12318965)"
4,I192064800,03114,Investigate Property,INVESTIGATE PROPERTY,E18,502,NaN,2019-08-17 19:39:00,2019,8,Saturday,19,Part Three,PHILBRICK ST,42.28545883,-71.11802667,"(42.28545883, -71.11802667)"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
413667,I020691165-00,03125,Warrant Arrests,WARRANT ARREST,A1,77,NaN,2019-05-23 08:00:00,2019,5,Thursday,8,Part Three,NEW SUDBURY ST,42.36183857,-71.05976489,"(42.36183857, -71.05976489)"
413668,I020674147-00,03125,Warrant Arrests,WARRANT ARREST,A1,77,NaN,2019-05-23 08:00:00,2019,5,Thursday,8,Part Three,NEW SUDBURY ST,42.36183857,-71.05976489,"(42.36183857, -71.05976489)"
413669,I020669075-00,03125,Warrant Arrests,WARRANT ARREST,A1,77,NaN,2019-05-23 08:00:00,2019,5,Thursday,8,Part Three,NEW SUDBURY ST,42.36183857,-71.05976489,"(42.36183857, -71.05976489)"
413670,I020662996-00,03125,Warrant Arrests,WARRANT ARREST,A1,77,NaN,2019-05-23 08:56:00,2019,5,Thursday,8,Part Three,NEW SUDBURY ST,42.36183857,-71.05976489,"(42.36183857, -71.05976489)"
413671,I010370257-00,03125,Warrant Arrests,WARRANT ARREST,E13,569,NaN,2016-05-31 19:35:00,2016,5,Tuesday,19,Part Three,NEW WASHINGTON ST,42.30233307,-71.11156487,"(42.30233307, -71.11156487)"

In [9]:
# To add a headers to an empty header dataframe like the one above, you can use perfix whose parameter is a string
df3=pd.read_csv("C:\\Users\\91830\\Downloads\\data science\\Ex_Files_Intro_Data_Science\\Exercise Files\\crime_boston.csv",skiprows=1,header=None,prefix='Data',dtype=object)
df3

,Data0,Data1,Data2,Data3,Data4,Data5,Data6,Data7,Data8,Data9,Data10,Data11,Data12,Data13,Data14,Data15,Data16
0,I192064813,03006,Medical Assistance,SICK/INJURED/MEDICAL - PERSON,D14,794,NaN,2019-08-17 21:00:00,2019,8,Saturday,21,Part Three,QUINT AVE,NaN,NaN,"(0.00000000, 0.00000000)"
1,I192064810,03410,Towed,TOWED MOTOR VEHICLE,B3,435,NaN,2019-08-17 21:15:00,2019,8,Saturday,21,Part Three,PEACEVALE RD,42.28716674,-71.07633479,"(42.28716674, -71.07633479)"
2,I192064808,02003,Offenses Against Child / Family,CHILD ENDANGERMENT (NO ASSAULT),C11,355,NaN,2019-08-17 19:33:00,2019,8,Saturday,19,Part Two,GIBSON ST,42.29755533,-71.0597091,"(42.29755533, -71.05970910)"
3,I192064803,00802,Simple Assault,ASSAULT SIMPLE - BATTERY,E18,554,NaN,2019-08-17 20:55:00,2019,8,Saturday,20,Part Two,METROPOLITAN AVE,42.27250898,-71.12318965,"(42.27250898, -71.12318965)"
4,I192064800,03114,Investigate Property,INVESTIGATE PROPERTY,E18,502,NaN,2019-08-17 19:39:00,2019,8,Saturday,19,Part Three,PHILBRICK ST,42.28545883,-71.11802667,"(42.28545883, -71.11802667)"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
413667,I020691165-00,03125,Warrant Arrests,WARRANT ARREST,A1,77,NaN,2019-05-23 08:00:00,2019,5,Thursday,8,Part Three,NEW SUDBURY ST,42.36183857,-71.05976489,"(42.36183857, -71.05976489)"
413668,I020674147-00,03125,Warrant Arrests,WARRANT ARREST,A1,77,NaN,2019-05-23 08:00:00,2019,5,Thursday,8,Part Three,NEW SUDBURY ST,42.36183857,-71.05976489,"(42.36183857, -71.05976489)"
413669,I020669075-00,03125,Warrant Arrests,WARRANT ARREST,A1,77,NaN,2019-05-23 08:00:00,2019,5,Thursday,8,Part Three,NEW SUDBURY ST,42.36183857,-71.05976489,"(42.36183857, -71.05976489)"
413670,I020662996-00,03125,Warrant Arrests,WARRANT ARREST,A1,77,NaN,2019-05-23 08:56:00,2019,5,Thursday,8,Part Three,NEW SUDBURY ST,42.36183857,-71.05976489,"(42.36183857, -71.05976489)"
413671,I010370257-00,03125,Warrant Arrests,WARRANT ARREST,E13,569,NaN,2016-05-31 19:35:00,2016,5,Tuesday,19,Part Three,NEW WASHINGTON ST,42.30233307,-71.11156487,"(42.30233307, -71.11156487)"

In [10]:
# Make sure that header is set to none

In [11]:
# To give names to headings we can use names with parameter as a list of names in string datatype
df4=pd.read_csv("C:\\Users\\91830\\Downloads\\data science\\Ex_Files_Intro_Data_Science\\Exercise Files\\crime_boston.csv",skiprows=1,names=['a','b','c','d','e','f','g','h','i','j','k','l','m'])
df4

,,,,a,b,c,d,e,f,g,h,i,j,k,l,m
I192064813,3006,Medical Assistance,SICK/INJURED/MEDICAL - PERSON,D14,794,NaN,2019-08-17 21:00:00,2019,8,Saturday,21,Part Three,QUINT AVE,NaN,NaN,"(0.00000000, 0.00000000)"
I192064810,3410,Towed,TOWED MOTOR VEHICLE,B3,435,NaN,2019-08-17 21:15:00,2019,8,Saturday,21,Part Three,PEACEVALE RD,42.287167,-71.076335,"(42.28716674, -71.07633479)"
I192064808,2003,Offenses Against Child / Family,CHILD ENDANGERMENT (NO ASSAULT),C11,355,NaN,2019-08-17 19:33:00,2019,8,Saturday,19,Part Two,GIBSON ST,42.297555,-71.059709,"(42.29755533, -71.05970910)"
I192064803,802,Simple Assault,ASSAULT SIMPLE - BATTERY,E18,554,NaN,2019-08-17 20:55:00,2019,8,Saturday,20,Part Two,METROPOLITAN AVE,42.272509,-71.123190,"(42.27250898, -71.12318965)"
I192064800,3114,Investigate Property,INVESTIGATE PROPERTY,E18,502,NaN,2019-08-17 19:39:00,2019,8,Saturday,19,Part Three,PHILBRICK ST,42.285459,-71.118027,"(42.28545883, -71.11802667)"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
I020691165-00,3125,Warrant Arrests,WARRANT ARREST,A1,77,NaN,2019-05-23 08:00:00,2019,5,Thursday,8,Part Three,NEW SUDBURY ST,42.361839,-71.059765,"(42.36183857, -71.05976489)"
I020674147-00,3125,Warrant Arrests,WARRANT ARREST,A1,77,NaN,2019-05-23 08:00:00,2019,5,Thursday,8,Part Three,NEW SUDBURY ST,42.361839,-71.059765,"(42.36183857, -71.05976489)"
I020669075-00,3125,Warrant Arrests,WARRANT ARREST,A1,77,NaN,2019-05-23 08:00:00,2019,5,Thursday,8,Part Three,NEW SUDBURY ST,42.361839,-71.059765,"(42.36183857, -71.05976489)"
I020662996-00,3125,Warrant Arrests,WARRANT ARREST,A1,77,NaN,2019-05-23 08:56:00,2019,5,Thursday,8,Part Three,NEW SUDBURY ST,42.361839,-71.059765,"(42.36183857, -71.05976489)"
I010370257-00,3125,Warrant Arrests,WARRANT ARREST,E13,569,NaN,2016-05-31 19:35:00,2016,5,Tuesday,19,Part Three,NEW WASHINGTON ST,42.302333,-71.111565,"(42.30233307, -71.11156487)"

## Pandas read_csv function methods

In [12]:
# Head method is used to print first rows(5 rows) of a dataframe
df.head()

,INCIDENT_NUMBER,OFFENSE_CODE,OFFENSE_CODE_GROUP,OFFENSE_DESCRIPTION,DISTRICT,REPORTING_AREA,SHOOTING,OCCURRED_ON_DATE,YEAR,MONTH,DAY_OF_WEEK,HOUR,UCR_PART,STREET,Lat,Long,Location
0,I192064813,3006,Medical Assistance,SICK/INJURED/MEDICAL - PERSON,D14,794,NaN,2019-08-17 21:00:00,2019,8,Saturday,21,Part Three,QUINT AVE,NaN,NaN,"(0.00000000, 0.00000000)"
1,I192064810,3410,Towed,TOWED MOTOR VEHICLE,B3,435,NaN,2019-08-17 21:15:00,2019,8,Saturday,21,Part Three,PEACEVALE RD,42.287167,-71.076335,"(42.28716674, -71.07633479)"
2,I192064808,2003,Offenses Against Child / Family,CHILD ENDANGERMENT (NO ASSAULT),C11,355,NaN,2019-08-17 19:33:00,2019,8,Saturday,19,Part Two,GIBSON ST,42.297555,-71.059709,"(42.29755533, -71.05970910)"
3,I192064803,802,Simple Assault,ASSAULT SIMPLE - BATTERY,E18,554,NaN,2019-08-17 20:55:00,2019,8,Saturday,20,Part Two,METROPOLITAN AVE,42.272509,-71.123190,"(42.27250898, -71.12318965)"
4,I192064800,3114,Investigate Property,INVESTIGATE PROPERTY,E18,502,NaN,2019-08-17 19:39:00,2019,8,Saturday,19,Part Three,PHILBRICK ST,42.285459,-71.118027,"(42.28545883, -71.11802667)"

In [13]:
# You can use parameter for head method print your desired number of rows
df.head(8)

,INCIDENT_NUMBER,OFFENSE_CODE,OFFENSE_CODE_GROUP,OFFENSE_DESCRIPTION,DISTRICT,REPORTING_AREA,SHOOTING,OCCURRED_ON_DATE,YEAR,MONTH,DAY_OF_WEEK,HOUR,UCR_PART,STREET,Lat,Long,Location
0,I192064813,3006,Medical Assistance,SICK/INJURED/MEDICAL - PERSON,D14,794,NaN,2019-08-17 21:00:00,2019,8,Saturday,21,Part Three,QUINT AVE,NaN,NaN,"(0.00000000, 0.00000000)"
1,I192064810,3410,Towed,TOWED MOTOR VEHICLE,B3,435,NaN,2019-08-17 21:15:00,2019,8,Saturday,21,Part Three,PEACEVALE RD,42.287167,-71.076335,"(42.28716674, -71.07633479)"
2,I192064808,2003,Offenses Against Child / Family,CHILD ENDANGERMENT (NO ASSAULT),C11,355,NaN,2019-08-17 19:33:00,2019,8,Saturday,19,Part Two,GIBSON ST,42.297555,-71.059709,"(42.29755533, -71.05970910)"
3,I192064803,802,Simple Assault,ASSAULT SIMPLE - BATTERY,E18,554,NaN,2019-08-17 20:55:00,2019,8,Saturday,20,Part Two,METROPOLITAN AVE,42.272509,-71.123190,"(42.27250898, -71.12318965)"
4,I192064800,3114,Investigate Property,INVESTIGATE PROPERTY,E18,502,NaN,2019-08-17 19:39:00,2019,8,Saturday,19,Part Three,PHILBRICK ST,42.285459,-71.118027,"(42.28545883, -71.11802667)"
5,I192064798,3006,Medical Assistance,SICK/INJURED/MEDICAL - PERSON,B3,422,NaN,2019-08-17 19:50:00,2019,8,Saturday,19,Part Three,RIVER ST,42.271324,-71.081835,"(42.27132363, -71.08183509)"
6,I192064797,802,Simple Assault,ASSAULT SIMPLE - BATTERY,B2,293,NaN,2019-08-17 19:43:00,2019,8,Saturday,19,Part Two,DORR ST,42.327292,-71.091590,"(42.32729205, -71.09159029)"
7,I192064795,3301,Verbal Disputes,VERBAL DISPUTE,E18,940,NaN,2019-08-17 19:56:00,2019,8,Saturday,19,Part Three,GARFIELD AVE,42.243619,-71.119893,"(42.24361883, -71.11989255)"

In [14]:
# Similarly tail method returns bottom 5 rows and returns specified number of rows if a parameter is given
df.tail()

,INCIDENT_NUMBER,OFFENSE_CODE,OFFENSE_CODE_GROUP,OFFENSE_DESCRIPTION,DISTRICT,REPORTING_AREA,SHOOTING,OCCURRED_ON_DATE,YEAR,MONTH,DAY_OF_WEEK,HOUR,UCR_PART,STREET,Lat,Long,Location
413667,I020691165-00,3125,Warrant Arrests,WARRANT ARREST,A1,77,NaN,2019-05-23 08:00:00,2019,5,Thursday,8,Part Three,NEW SUDBURY ST,42.361839,-71.059765,"(42.36183857, -71.05976489)"
413668,I020674147-00,3125,Warrant Arrests,WARRANT ARREST,A1,77,NaN,2019-05-23 08:00:00,2019,5,Thursday,8,Part Three,NEW SUDBURY ST,42.361839,-71.059765,"(42.36183857, -71.05976489)"
413669,I020669075-00,3125,Warrant Arrests,WARRANT ARREST,A1,77,NaN,2019-05-23 08:00:00,2019,5,Thursday,8,Part Three,NEW SUDBURY ST,42.361839,-71.059765,"(42.36183857, -71.05976489)"
413670,I020662996-00,3125,Warrant Arrests,WARRANT ARREST,A1,77,NaN,2019-05-23 08:56:00,2019,5,Thursday,8,Part Three,NEW SUDBURY ST,42.361839,-71.059765,"(42.36183857, -71.05976489)"
413671,I010370257-00,3125,Warrant Arrests,WARRANT ARREST,E13,569,NaN,2016-05-31 19:35:00,2016,5,Tuesday,19,Part Three,NEW WASHINGTON ST,42.302333,-71.111565,"(42.30233307, -71.11156487)"

In [15]:
df.tail(8)

,INCIDENT_NUMBER,OFFENSE_CODE,OFFENSE_CODE_GROUP,OFFENSE_DESCRIPTION,DISTRICT,REPORTING_AREA,SHOOTING,OCCURRED_ON_DATE,YEAR,MONTH,DAY_OF_WEEK,HOUR,UCR_PART,STREET,Lat,Long,Location
413664,I030217815-08,111,Homicide,"MURDER, NON-NEGLIGIENT MANSLAUGHTER",E18,520,NaN,2015-07-09 13:38:00,2015,7,Thursday,13,Part One,RIVER ST,42.255926,-71.123172,"(42.25592648, -71.12317207)"
413665,I020695506-00,1806,Drug Violation,DRUGS - CLASS B TRAFFICKING OVER 18 GRAMS,A1,77,NaN,2019-05-23 08:00:00,2019,5,Thursday,8,Part Two,NEW SUDBURY ST,42.361839,-71.059765,"(42.36183857, -71.05976489)"
413666,I020695210-00,1843,Drug Violation,DRUGS - POSS CLASS B - INTENT TO MFR DIST DISP,A1,77,NaN,2019-05-23 09:00:00,2019,5,Thursday,9,Part Two,NEW SUDBURY ST,42.361839,-71.059765,"(42.36183857, -71.05976489)"
413667,I020691165-00,3125,Warrant Arrests,WARRANT ARREST,A1,77,NaN,2019-05-23 08:00:00,2019,5,Thursday,8,Part Three,NEW SUDBURY ST,42.361839,-71.059765,"(42.36183857, -71.05976489)"
413668,I020674147-00,3125,Warrant Arrests,WARRANT ARREST,A1,77,NaN,2019-05-23 08:00:00,2019,5,Thursday,8,Part Three,NEW SUDBURY ST,42.361839,-71.059765,"(42.36183857, -71.05976489)"
413669,I020669075-00,3125,Warrant Arrests,WARRANT ARREST,A1,77,NaN,2019-05-23 08:00:00,2019,5,Thursday,8,Part Three,NEW SUDBURY ST,42.361839,-71.059765,"(42.36183857, -71.05976489)"
413670,I020662996-00,3125,Warrant Arrests,WARRANT ARREST,A1,77,NaN,2019-05-23 08:56:00,2019,5,Thursday,8,Part Three,NEW SUDBURY ST,42.361839,-71.059765,"(42.36183857, -71.05976489)"
413671,I010370257-00,3125,Warrant Arrests,WARRANT ARREST,E13,569,NaN,2016-05-31 19:35:00,2016,5,Tuesday,19,Part Three,NEW WASHINGTON ST,42.302333,-71.111565,"(42.30233307, -71.11156487)"

In [22]:
# To change datatype of a particular column we use dtype parameter where we use dictionary with the key as the column name
# and the value as the datatype
df5=pd.read_csv("C:\\Users\\91830\\Downloads\\data science\\Ex_Files_Intro_Data_Science\\Exercise Files\\crime_boston.csv",dtype={"OFFENSE_CODE":"float64","MONTH":"float64"})
df5

,INCIDENT_NUMBER,OFFENSE_CODE,OFFENSE_CODE_GROUP,OFFENSE_DESCRIPTION,DISTRICT,REPORTING_AREA,SHOOTING,OCCURRED_ON_DATE,YEAR,MONTH,DAY_OF_WEEK,HOUR,UCR_PART,STREET,Lat,Long,Location
0,I192064813,3006.0,Medical Assistance,SICK/INJURED/MEDICAL - PERSON,D14,794,NaN,2019-08-17 21:00:00,2019,8.0,Saturday,21,Part Three,QUINT AVE,NaN,NaN,"(0.00000000, 0.00000000)"
1,I192064810,3410.0,Towed,TOWED MOTOR VEHICLE,B3,435,NaN,2019-08-17 21:15:00,2019,8.0,Saturday,21,Part Three,PEACEVALE RD,42.287167,-71.076335,"(42.28716674, -71.07633479)"
2,I192064808,2003.0,Offenses Against Child / Family,CHILD ENDANGERMENT (NO ASSAULT),C11,355,NaN,2019-08-17 19:33:00,2019,8.0,Saturday,19,Part Two,GIBSON ST,42.297555,-71.059709,"(42.29755533, -71.05970910)"
3,I192064803,802.0,Simple Assault,ASSAULT SIMPLE - BATTERY,E18,554,NaN,2019-08-17 20:55:00,2019,8.0,Saturday,20,Part Two,METROPOLITAN AVE,42.272509,-71.123190,"(42.27250898, -71.12318965)"
4,I192064800,3114.0,Investigate Property,INVESTIGATE PROPERTY,E18,502,NaN,2019-08-17 19:39:00,2019,8.0,Saturday,19,Part Three,PHILBRICK ST,42.285459,-71.118027,"(42.28545883, -71.11802667)"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
413667,I020691165-00,3125.0,Warrant Arrests,WARRANT ARREST,A1,77,NaN,2019-05-23 08:00:00,2019,5.0,Thursday,8,Part Three,NEW SUDBURY ST,42.361839,-71.059765,"(42.36183857, -71.05976489)"
413668,I020674147-00,3125.0,Warrant Arrests,WARRANT ARREST,A1,77,NaN,2019-05-23 08:00:00,2019,5.0,Thursday,8,Part Three,NEW SUDBURY ST,42.361839,-71.059765,"(42.36183857, -71.05976489)"
413669,I020669075-00,3125.0,Warrant Arrests,WARRANT ARREST,A1,77,NaN,2019-05-23 08:00:00,2019,5.0,Thursday,8,Part Three,NEW SUDBURY ST,42.361839,-71.059765,"(42.36183857, -71.05976489)"
413670,I020662996-00,3125.0,Warrant Arrests,WARRANT ARREST,A1,77,NaN,2019-05-23 08:56:00,2019,5.0,Thursday,8,Part Three,NEW SUDBURY ST,42.361839,-71.059765,"(42.36183857, -71.05976489)"
413671,I010370257-00,3125.0,Warrant Arrests,WARRANT ARREST,E13,569,NaN,2016-05-31 19:35:00,2016,5.0,Tuesday,19,Part Three,NEW WASHINGTON ST,42.302333,-71.111565,"(42.30233307, -71.11156487)"